/**
 * GRBL-compliant G-code emission.
 *
 * Deliberately restricted to what GRBL 1.1 actually parses: no canned cycles
 * (`G81`), no tool length offsets (`G43`), no arcs. Everything is `G0`/`G1`
 * linear motion, which any grbl or grblHAL build will accept without a
 * "unsupported command" alarm mid-job.
 *
 * The toolpath is millimetres throughout; conversion to inches happens here and
 * only here.
 */

import { MM_PER_INCH, type Project, type Units } from "./project";
import type { Toolpath } from "./toolpath";

export type GcodeMeta = {
	/** Free-text lines added to the header, e.g. font and strategy. */
	notes?: string[];
};

const decimalsFor = (units: Units): number => (units === "in" ? 4 : 3);

/** Formats a value, trimming trailing zeros but keeping at least one digit. */
const fmt = (value: number, decimals: number): string => {
	// Avoid "-0.000" — GRBL accepts it, but it reads like a bug in the output.
	const safe = Object.is(value, -0) ? 0 : value;
	const fixed = safe.toFixed(decimals);
	return fixed.replace(/(\.\d*?)0+$/, "$1").replace(/\.$/, "");
};

/** Escapes G-code comment delimiters, which cannot nest. */
const comment = (text: string): string => `(${text.replace(/[()]/g, "")})`;

export const emitGcode = (
	toolpath: Toolpath,
	project: Project,
	meta: GcodeMeta = {},
): string => {
	const { units, tool } = project;
	const dec = decimalsFor(units);
	const scale = units === "in" ? 1 / MM_PER_INCH : 1;

	const xyz = (v: number) => fmt(v * scale, dec);
	// Feeds are per-minute in the active units, so they scale the same way.
	const feed = (v: number) => fmt(v * scale, units === "in" ? 2 : 1);

	const lines: string[] = [];

	lines.push(comment("Generated by Simple Signs - gSender plugin"));
	lines.push(comment(`Units: ${units}`));
	lines.push(
		comment(
			`Blank: ${project.blank.shape} ${fmt(project.blank.width, 2)} x ${fmt(project.blank.height, 2)} mm, depth ${fmt(project.blank.depth, 2)} mm`,
		),
	);
	lines.push(
		comment(
			`Text: "${project.text.content.replace(/\r?\n/g, " / ")}" - ${project.text.strategy}, depth ${fmt(project.text.depth, 2)} mm`,
		),
	);
	lines.push(
		comment(
			`Tool: endmill ${fmt(tool.endmillDiameter, 3)} mm`,
		),
	);
	lines.push(
		comment(
			`Feeds: cut ${fmt(tool.feedrate, 0)}, plunge ${fmt(tool.plungeRate, 0)} mm/min, spindle ${fmt(tool.spindleRpm, 0)} RPM`,
		),
	);
	if (project.tabs.enabled && project.tabs.positions.length > 0) {
		lines.push(
			comment(
				`Tabs: ${project.tabs.positions.length} x ${fmt(project.tabs.length, 2)} mm long, ${fmt(project.tabs.height, 2)} mm tall`,
			),
		);
		lines.push(
			comment(
				`Tab positions (% around profile): ${project.tabs.positions
					.map((p) => (p * 100).toFixed(1))
					.join(", ")}`,
			),
		);
	}
	lines.push(comment(`Work origin: ${project.origin === "center" ? "blank centre" : "lower-left of blank"}`));
	for (const note of meta.notes ?? []) lines.push(comment(note));
	for (const warning of toolpath.warnings) lines.push(comment(`WARNING: ${warning}`));

	// Preamble.
	lines.push(units === "in" ? "G20" : "G21");
	lines.push("G90");
	lines.push("G17");
	lines.push("G94");
	lines.push(`M3 S${fmt(tool.spindleRpm, 0)}`);
	if (tool.spindleDwell > 0) lines.push(`G4 P${fmt(tool.spindleDwell, 2)}`);

	const safeZ = xyz(tool.safeZ);
	lines.push(`G0 Z${safeZ}`);

	// Modal state, so we only emit words that actually change.
	let lastX: number | null = null;
	let lastY: number | null = null;
	let lastZ: number | null = null;
	let lastF: number | null = null;

	const axisWords = (
		x: number | null,
		y: number | null,
		z: number | null,
	): string => {
		let out = "";
		if (x !== null && x !== lastX) out += ` X${xyz(x)}`;
		if (y !== null && y !== lastY) out += ` Y${xyz(y)}`;
		if (z !== null && z !== lastZ) out += ` Z${xyz(z)}`;
		return out;
	};

	const commit = (x: number | null, y: number | null, z: number | null) => {
		if (x !== null) lastX = x;
		if (y !== null) lastY = y;
		if (z !== null) lastZ = z;
	};

	const feedWord = (rate: number): string => {
		if (lastF === rate) return "";
		lastF = rate;
		return ` F${feed(rate)}`;
	};

	for (const pass of toolpath.passes) {
		if (pass.moves.length === 0) continue;
		if (pass.comment) lines.push(comment(pass.comment));

		const [first, ...rest] = pass.moves;

		// Position over the start point at safe height, then plunge.
		const approach = axisWords(first.x, first.y, null);
		if (approach) {
			lines.push(`G0${approach}`);
			commit(first.x, first.y, null);
		}

		const plunge = axisWords(null, null, first.z);
		if (plunge) {
			lines.push(`G1${plunge}${feedWord(pass.plunge)}`);
			commit(null, null, first.z);
		}

		for (const move of rest) {
			const words = axisWords(move.x, move.y, move.z);
			// Nothing changed — a duplicate vertex. Skip rather than emit a bare
			// "G1", which some senders treat as an error.
			if (!words) continue;
			lines.push(`G1${words}${feedWord(pass.feed)}`);
			commit(move.x, move.y, move.z);
		}

		lines.push(`G0 Z${safeZ}`);
		lastZ = tool.safeZ;
	}

	lines.push("M5");
	lines.push("M30");

	return `${lines.join("\n")}\n`;
};

/**
 * Extracts the distinct G/M words used in a program. Used by the tests to
 * assert we never emit anything outside GRBL's supported set.
 */
export const gcodeWordsUsed = (gcode: string): string[] => {
	const words = new Set<string>();
	for (const rawLine of gcode.split("\n")) {
		const line = rawLine.replace(/\([^)]*\)/g, "").trim();
		if (!line) continue;
		for (const match of line.matchAll(/\b([GM])(\d+(?:\.\d+)?)\b/g)) {
			words.add(`${match[1]}${Number(match[2])}`);
		}
	}
	return [...words].sort();
};
